version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - oed
  assignees:
  - oed
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: did-resolver
    versions:
    - 2.2.0
    - 3.0.1
    - 3.0.2
